export { default as CloseEyeIcon } from './closeEye.svg?react'
export { default as OpenEyeIcon } from './openEye.svg?react'
export { default as SearchIcon } from './search.svg?react'
export { default as GithubIcon } from './social/github.svg?react'
export { default as GoogleIcon } from './social/google.svg?react'
